### PR TITLE
Addedjobname

### PR DESCRIPTION
**Pull request by uxi187**
Added option to show Circle CI Job name under the slack message. Very useful for the workflow with multiple jobs.

### CODE REVIEW

**Comment by YOU54F** [comment]
Hey thanks for the PR, 

Could you remove the package lock file as this project uses yarn, and could you add a test so the coverage doesn't drop and we'll get it committed 👌

**Comment by YOU54F** [comment]
@uxi187 changes now incorporated and released at v0.5.0. I have squashed the commits as they didn't meet commitlog conventions. Thanks for your contribution.

**Comment by uxi187** [comment]
Hi mate,

Sorry for the late response I didn't have time to complete tests, but I
started working on them.
Should I complete and push them?

**Comment by YOU54F** [comment]
No need @uxi187, you changes are in now and released

**Pull request closed without merging**
