### PR TITLE
feat(ci-provider): added option for Jenkins CI provider

### PR DESCRIPTION
**Pull request by YOU54F**
Thanks @mikepsinn for the change

### CODE REVIEW

**Comment by mikepsinn** [comment]
Sure! Thanks for all your great work here, @YOU54F !

**Comment by AmeanAsad** [comment]
Hello!@YOU54F will you be merging this to the main repo anytime soon?

**Comment by YOU54F** [comment]
yeah sorry @AmeanAsad I did mean to increase the code coverage prior to merging, but I will resolve the conflicts and get this merged now

**Comment by YOU54F** [comment]
sorry @mikepsinn for the extended delay, this will be going out once the ci tests have passed so should be with you in around 30 mins

**Comment by YOU54F** [comment]
released as `v0.8.0` 🚀

**Comment by AmeanAsad** [comment]
Thanks @YOU54F for merging! I have a quick question, is there a guide to what environment variables to set for Jenkins or is it just the same setup as circle-CI?

**Comment by YOU54F** [comment]
If you check

https://github.com/YOU54F/cypress-slack-reporter/blob/f8bd42fde2303ef49e34f6d55d0f33e4fc3531fd/src/slack/slack-alert.ts#L488

and here

https://github.com/YOU54F/cypress-slack-reporter/blob/master/config.env.test.jenkins

There isn't any info in the readme but happy to accept a PR if you want to provide

**Pull request merged**
