### PR TITLE
feat: custom test page url set

### LINKED ISSUE #497: Custom URI, for notifications link
Hello,

First of all, many thanks for the good job, your plugin is really usefull.
I would like to know if you could offer an option for a custom base URI, which allow a user to pass a custom BASE_URI for the videos and screenshots links.

For example if you put 
`npx cypress-slack-reporter --ci-provider none --vcs-provider none`
Do you think it will be possible to offer a custom URI which allow to _artefactUrl
For the moment, I replace 'default' value in getArtefactUrl() but it would be better with a bash option, but I don't really understand how it works :) 

Thanks in advance for your help.

### PR DESCRIPTION
**Pull request by saikatharryc**
fixes #497

### CODE REVIEW

**Comment by saikatharryc** [comment]
I need some help/guidance on how to test locally. as my `npm test` gives this:
```
$ jest --coverage
TypeError: _gracefulFs(...).realpathSync.native is not a function
    at tryRealpath (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-util/build/tryRealpath.js:26:39)
    at getCacheDirectory (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-config/build/getCacheDirectory.js:89:33)
    at Object.<anonymous> (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-config/build/Defaults.js:39:50)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

**Comment by YOU54F** [comment]
> I need some help/guidance on how to test locally. as my `npm test` gives this:
> 
> ```
> $ jest --coverage
> TypeError: _gracefulFs(...).realpathSync.native is not a function
>     at tryRealpath (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-util/build/tryRealpath.js:26:39)
>     at getCacheDirectory (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-config/build/getCacheDirectory.js:89:33)
>     at Object.<anonymous> (/Users/I523974/Desktop/cypress-slack-reporter/node_modules/jest-config/build/Defaults.js:39:50)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Module.require (module.js:597:17)
>     at require (internal/module.js:11:18)
> error Command failed with exit code 1.
> ```

That's weird! Are you running in windows? Can you provide some details of your local setup? node version / shell version etc

**Comment by saikatharryc** [comment]
@YOU54F
I'm using Mac & Node v8.16.2.

although now I can see its passing.
but it will be great if someone can test or have a look at the same.

**Comment by YOU54F** [comment]
Looks fine on my machine - also a Mac but running node 12. I assume you are running the oval jest and not global? As it uses ts-jest.

Could you document the change in the readme please and add a test and I will be happy to merge and release. 👌

**Comment by saikatharryc** [comment]
@YOU54F  the circle CI is failing, can you have a look at it once maybe?
its. passing in my local. and here also (in circleci) sometimes it's passing sometimes not.
is the ENV set in the ci?

**Comment by saikatharryc** [comment]
@YOU54F bringing this to your notice! any help would be helpful on this!
I guess the webhook is not set in the pipeline or something?

**Comment by YOU54F** [comment]
Released as v0.7.1

**Pull request merged**
